### ISSUE TITLE
Refactorer les activités en fragments

### ISSUE THREAD

**Issue by socatoa** [arteymix/guide-des-medicaments#6]
Ce serait plus agréable d'avoir une navigation par tabs http://developer.android.com/design/building-blocks/tabs.html
- bookmarks
- panier
- résultats de recherche

**Comment by arteymix** [comment]
J'ai pas mal terminé de transformer les résultats de recherche en fragment, on va pouvoir les intégrer
dans le panier et dans l'activité principale :)

**Comment by socatoa** [comment]
Cool!
Sinon on a fini le ppt, il reste juste à faire quelques screenshots & it's done!
Voici le ppt

Date: Wed, 22 Apr 2015 13:54:06 -0700

**Comment by arteymix** [comment]
J'ai pas mal terminé les modifications :+1: 

Okay, je vous envoi les screenshot depuis mon téléphone!
